=== bigfnj/desktop-ai-companion/src/Resources/animations.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    targetNamespace="https://esheep.petrucci.ch/"
    xmlns="https://esheep.petrucci.ch/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name='animations'>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name='header' minOccurs='1' maxOccurs='1'>
          <xsd:annotation>
            <xsd:documentation>Main informations about this Pet.</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name='author' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Author of the animation, insert your name or full name.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='title' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Title of the animation, used on the webpage.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='petname' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Name of your pet. Displayed on the contextmenu.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='version' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Insert the application version, 0.1 for a beta. Once it is published you can't change it anymore.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='info' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Info about the animation, write some sentences, credits and your email if you want.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='application' type='xsd:integer' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Application version, this must be set to 1, because this is the current and only version.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='icon' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Icon as CDATA base64 encoded, see https://esheep.petrucci.ch/?p=tools&amp;s=icon to convert a PNG to ICO and https://esheep.petrucci.ch/?p=tools&amp;s=base64 to convert it to a base64 string.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name='image'>
          <xsd:annotation>
            <xsd:documentation>All informations about the sprite image sheet.</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name='tilesx' type='xsd:integer' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>How much images are on the x axis (tiles) of the sprite sheet.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='tilesy' type='xsd:integer' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>How much images are on the y axis (tiles) of the sprite sheet.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='png' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Sprite sheet as CDATA base64 encoded, see https://esheep.petrucci.ch/?p=tools&amp;s=base64 to convert it to a base64 string.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name='transparency' type='xsd:string' minOccurs='1' maxOccurs='1'>
                <xsd:annotation>
                  <xsd:documentation>Transparency: color key used to show transparency. Default: Magenta</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name='spawns'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='spawn' maxOccurs='unbounded'>
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='next' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base='xsd:integer'>
                            <xsd:attribute name="probability" type="xsd:integer" />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:all>
                  <xsd:attribute name="probability" type="xsd:integer"/>
                  <xsd:attribute name="id" type="xsd:int"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name='animations'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='animation' minOccurs='1' maxOccurs='unbounded'>
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name='name' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='start' minOccurs='1' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:group ref="step"/>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name='end' minOccurs='1' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:group ref="step"/>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name='sequence' minOccurs='1' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded">
                          <xsd:element name='frame' type='xsd:integer' minOccurs='1' maxOccurs='unbounded' />
                          <xsd:element name='action' type='xsd:string' minOccurs='0' />
                          <xsd:element ref='next' />
                        </xsd:choice>
                        <xsd:attribute name="repeat" type="xsd:string"/>
                        <xsd:attribute name="repeatfrom" type="xsd:integer"/>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name='border' minOccurs='0' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:choice maxOccurs="256">
                          <xsd:element ref='next' />
                        </xsd:choice>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name='gravity' minOccurs='0' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:choice maxOccurs="256">
                          <xsd:element ref='next' />
                        </xsd:choice>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:all>
                  <xsd:attribute name="id" type="xsd:integer"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name='childs'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='child' minOccurs='0' maxOccurs='unbounded'>
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='next' maxOccurs='1'>
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base='xsd:integer'>
                            <xsd:attribute name="probability" type="xsd:integer" />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:all>
                  <xsd:attribute name="animationid" type="xsd:int"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name='sounds' minOccurs='0' maxOccurs='1'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='sound' minOccurs='0' maxOccurs='unbounded'>
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name='probability' type='xsd:integer' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='loop' type='xsd:integer' minOccurs='0' maxOccurs='1' />
                    <xsd:element name='base64' type='xsd:string' minOccurs='1' maxOccurs='1' />
                  </xsd:all>
                  <xsd:attribute name="animationid" type="xsd:int"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:simpleType name="borderType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="none" />
      <xsd:enumeration value="taskbar" />
      <xsd:enumeration value="window" />
      <xsd:enumeration value="horizontal" />
      <xsd:enumeration value="horizontal+" />
      <xsd:enumeration value="vertical" />
      <!-- Which EDGE of a window the pet reached. "window" above stays the wildcard that fires at all
           three, so a pet written before these existed is unaffected. -->
      <xsd:enumeration value="window-left" />
      <xsd:enumeration value="window-right" />
      <xsd:enumeration value="window-top" />
      <xsd:enumeration value="window-bottom" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:group name="step">
    <xsd:all>
      <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
      <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
      <xsd:element name='offsety' type='xsd:integer' minOccurs='0' maxOccurs='1' default='0' />
      <xsd:element name='opacity' type='xsd:double' minOccurs='0' maxOccurs='1' default='1.0' />
      <xsd:element name='interval' type='xsd:string' minOccurs='1' maxOccurs='1' />
    </xsd:all>
  </xsd:group>
  
  <xsd:element name="next">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base='xsd:integer'>
          <xsd:attribute name="probability" type="xsd:integer" />
          <xsd:attribute name="only" type="borderType" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="only">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="next" />
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== bigfnj/desktop-ai-companion/modules/PetStudio/Resources/selftest-companion.xml
<?xml version="1.0"?>
<animations xmlns="https://esheep.petrucci.ch/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://esheep.petrucci.ch/ https://raw.githubusercontent.com/Adrianotiger/desktopPet/master/Resources/animations.xsd">
<header>
<author>Adriano</author>
<title>eSheep 64bit</title>
<petname>eSheep</petname>
<version>1.8</version>
<info>PetStudio self-test fixture: the bundled eSheep graph with a 64x44 placeholder sheet. Open source project for the lovely eSheep.[br] For more info, visit my webpage [link:https://esheep.petrucci.ch] [br]Image rip by LiL_Stenly</info>
<application>1</application>
<icon><![CDATA[AAABAAEAMDAAAAEAIACoJQAAFgAAACgAAAAwAAAAYAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzE1eev9yk8z/V4LM/z9zzP8AAAD/AAAA1gAAAMwAAAB6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMAAAAzAAAAOozPlH/eZjM/12GzP8/c8z/DBco/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzGB1mP+PuP//baP+/06P//8AAAD/JUV6/xIiPf8AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/JUV6/xIiPf9ATmX/mL7//3Wo//9PkP//Dxwz/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzGB1mP+PuP7/baP+/06P//8AAAD/P3PM/x85Zf8AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/P3PL/x85Zf9ATmX/mL7+/3Wo//9PkP//Dxwz/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzFZvmP+CsP7/Z5///0+Q//8AAAD/P3PM/x85Zf8AAACYAAAAAAAAAAAAAAAAAAAAKAAAADIAAAAyAAAAMgAAADIAAAD/Mlyj/xkuUf85SmX/ibX//22j//9PkP//Dxwz/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzC9WmP9PkP//T5D//0+Q//8AAAD/P3PM/x85Zf8AAACYAAAAAAAAAAAAAAAAAAAAzAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8fOWX/To/+/0+Q//9PkP//Dxwz/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Un6C/2eeo/9nnqP/Zp2i/2eeo/9nnqP/Zp2i/yk/Qf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMRGls9FJ+gv9SfoL/Un6C/1J+gv9SfoL/Un6C/yAyNP8gMjT/Un6C/1J+gv9SfoL/Ypec/2eeo/9nnqP/Z56j/2eeo/9nnqP/Zp2i/1qLj/9SfoL/Un6C/1J+gv9SfoL/Un6C/yU5O+AAAADMAAAAogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAJg9XmH/XpGV/2eeo/9nnqP/Z56j/2ado/9mnaP/Z56j/054e/9OeHv/Z56j/2eeo/9nnqP/Z56j/2eeo/9rpar/cKyx/2eeo/9nnqP/Z56j/2eeo/9nnqP/Z56j/2eeo/9nnqP/Z56j/054e/89XmH/NVJV6gAAAJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmAAAAZgAAAGYAAABmDxgZhCk/Qf9nnqP/Zp2i/2eeo/9nnqP/Z56j/2eeo/9nnqP/Z56j/2ado/9mnaP/Z56j/2ado/9uqa//bqmv/26pr/9zsbb/drW7/2ado/9mnaP/Z56j/2ado/9mnaP/Z56j/2ado/9mnaP/baes/26pr/9rpar/WouP/yk/Qf8AAABmAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAMgAAADIPHDP/Dxwz/w8cM/8JER7/FB8g/2eeo/9nnqP/Z56j/2mhpv9qpKn/aqKn/2eeo/9nnqP/Zp6j/2eeo/9nnqP/Zp2i/2eeo/92trv/ebrA/3q7wv94ub//c7G2/2eeo/9qpKn/aqSp/2qkqf9poab/Zp2i/2eeo/9qpKn/dre9/3q7wv9zsrj/aqSp/2qkqf8UHyD/CxESXAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmAAAA/wAAAP9PkP//T4///0+Q//8vVpj/FB8g/2eeo/9nnqP/Z56j/3Kwtf96vML/dra7/2eeo/9nnqP/Z56j/2ado/9mnaP/Z56j/2eeo/9nnqP/dra7/3m7wv9ysLX/Z56j/2eeo/96vML/erzC/3m7wv9ysLX/Z56j/2eeo/96vML/erzC/3m7wv96vML/ebzB/3q8wv9nnqP/FB8g/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgfOWb/TpD//0+Q//9PkP//T4///0+Q//8vVpj/GCUm/3q8wv96vML/ebzC/3q8wv9ysLX/Z56j/2eeo/9nnqP/Z56j/3Kwtf95u8L/erzC/3q8wv9nnqP/Z56j/3Kwtf95u8L/erzC/3q8wv96vML/erzC/3m7wv95u8L/erzC/3q8wv96vML/erzC/3m7wv96vML/ebzB/3q8wv96vML/ebzB/zBLTf8AAACYAAAAAAAAAAAAAAAAAAAAAAAAAJgfOWb/T5D+/0+Q//9PkP//T5D//0+Q//8vVpj/FSAh/2qkqf9qpKn/dre9/3Cts/9poab/aqKn/3a1u/92tbv/drW7/3i5v/96vMH/ebvB/3q8wv92trv/drW7/3i5v/96vMH/fcXL/4zq8v+M6vL/fcXL/3q8wf96vMH/fcXL/4zq8v+M6vL/fcXL/3q8wf95u8H/erzC/3q8wf+M6vL/jOry/zhdYf8AAACYAAAAAAAAAAAAAAAAAAAAeiE9bdY8bcH/U5L+/2We//9lnv//ZZ7//1iV//9CeNb/LlGH/yk/Qf9nnqP/dra7/3W0uv9ysLX/c7K4/3q8wv96vML/ervC/4LQ1/+H3ub/h97m/4fe5v+H3ub/fMLJ/4LQ1/+H3ub/iePr/5H1//+D09r/e8DG/3q8wv96u8L/e8DG/4PT2v+R9f//iePr/3/J0P9/ydD/h97m/4fe5v+R9v//kPX//266wf8+aW3WAAAAegAAAAAAAABmHDRc4EVzwf9emf//Ypz//3Wn//91p///daj//2ef//9emf7/UYbg/x85Zf89XmH/bamu/3q8wv96vML/erzC/3q8wv96vML/erzC/4LQ1/+H3ub/h97m/4fe5v+R9f//hdrh/4vo8P+R9v//j/H6/4fe5v+D09r/g9Pa/4PT2v+D09r/gc7V/3m7wv+H3ub/j/H6/4jh6f+I4en/j/H6/4fe5v+H3ub/h97m/4fe5v9RhYr/AAAAzAAAAAAAAAD/RXfL/2ig//91qP//daj//3Wo//91qP//dKf+/3Wo//91qP//bqT//1aU//8PHDP/UX6G/3Cssv96vML/erzC/3q8wv9+x87/fsfO/37Hzv9+x87/fsfO/37Hzv+M6vL/kPP8/5H2//+P8fr/iePr/37Hzv+R9v//kfb//5H2//+P8fr/iOHp/3q8wv96vML/iOHp/4/x+v+R9v//jez1/37Hzv9+x87/er7E/3q8wv9Sf4P/FyMk1gAAADIAAAD/XYbM/3Wo//91p/7/daf//3Wo//91qP//daf//3Wn//91qP//dKj//3Wo//9PkP//Dxwy/0lwdP96vML/ebzC/3q8wv+R9v//kfb//5H1//+R9f//kfb//5H2//96vML/jOry/5H1//+H3ub/fsfO/5H2//+R9v//kfb//5H1//+H3ub/erzC/3q8wv96vML/erzC/4fe5v+R9v//kPb//5H2//+R9v//fsfO/3q8wv96vML/YZab/wAAAP8AAAD/XYbM/3Wo//91p/7/fa3//6HE//+hxP//oMT//6HE//+PuP//dKj//3Wo//91qP//FyEy/0lwdP96vML/fsfO/5H2//96vML/erzC/3m7wv+D09r/kfb//5H2//+R9v//kfb//5H1//+R9f//kfb//5H2//+R9v//kfb//4PT2v+D09r/kfb//5H2//+R9v//kfb//4PT2v96vML/fsfO/5H2//+R9v//kPb//5H2//+H3ub/YZab/wAAAP8AAAD/XYbM/3Wo//+DsP7/mb/+/6HD//+hw///ocT//6DD//+dwf//mL7+/5i+//91qP//FyEy/0lwdP95vML/er7E/37Hzv+M6vL/jOry/4zq8v+O7/f/kPb+/5H2//+R9v//kPb+/5H1/v+R9f7/kPb+/5H2//+R9v//kPb+/47v9/+O7/f/kPb+/5H2//+R9v//kPb+/47v9/+M6vL/jez1/5D2/v+Q9v7/kPb//5D1/v+P8fr/cLvC/wAAAP8AAAD/XYbM/4Sy//+Wvf//ocT+/6HE//+hxP//ocT//6HE//+hxP7/ocT//6HE//+PuP//HCQy/0lwdP9/ydD/h97m/4fe5v+R9v//kfb+/5H2//+R9v//i+vz/3fBx/93wcf/d8HH/3fBx/+B1t3/kfX+/5H1//+R9f//kfb//5H2//+R9v//kfX+/5H1//+R9f//kfb//5H2//+R9v//kPX//5H2//+R9v//kPX//5H2//+R9v//dMTM/wAAAP8AAAD/d5fM/5zB//+hxP//ocT//6HE//+hxP//ocT//6HE//+hxP7/ocT//6HE//+hxP//U2WE/0Vjbv9lpqv/kfb//5H2//+R9v//kfb+/4bg6P+A0tr/crvC/z1eYf89XmH/PV5h/z1eYf9YjZH/gNLa/4DS2v+R9f//kfb//5H1//+R9v//kfX+/5H1//+R9f//kfb//5H1//+R9v//kfb//5H2//+R9v//kfb//5H2//+R9v//dMTM/wAAAP8AAADMhJKp9KS+6v+lxv//ocT//6HD//+hw///ocP+/6HE//+hxP//ocT//6HE//+hxP//ocT//0BOZv86Ymb/kfb//5H2//+I5Oz/iOTs/2inrP9SfoL/SWVv/yMAI/8XABf/FwAX/x4AHv82Mkn/Un6C/1J+gv+I5Oz/j/L7/5H2//+R9v//kPb+/5H2//+R9v//kfb//5H2//+R9v//kfX+/5D2/v+Q9v7/kfX//5H2//+W9v//f8XM/wAAAP8AAAAAAAAAzHeEmf+30v7/ocT//6HE//+hxP//oMT//6HE//+hxP//ocT//6HE//+hxP//ocT//0BOZv86Ymb/kfb//5H2//9nnqP/Z56j/yk/Qf8AAAD/IwAj/7MAs/9zAHP/cwBz/5kAmf9rAGv/AAAA/wAAAP9nnqP/iOTs/5H1//+R9f//kfb//5H2//+R9v//kfb//5H1//+R9v//kPb//5H2//+R9v//kPb//5H2//+t+P//rcnM/wAAAP8AAAAAAAAAAAAAAJhPWGb/v9f//6HE//+hxP//oMT//6HE//9gdZj/AAAA/wAAAP8AAAD/gJzM/6HE//9gdZj/FB8g/2eeo/9nnqP/FB8g/0UARf9zAHP/cwBz/3MAc/9zAHP/pgCm/4wAjP9zAHP/cwBz/3MAc/8AAAD/c8TL/5H1//+R9f//kfb//5H2//+R9v//kfb//5H1//+R9v//kPb//5H2//+R9v//kPb//5H2//+t+P//rcnM/wAAAP8AAAAAAAAAAAAAAB4eISeERk5b/7/X//+hw///ocT//1NlhP9kaXD/w8PD/6Ojo/+jo6P/OkBJ/22Frf+UtOr/a4Op/xQfIP8UHyD/TQZQ/2kAaf9OAE7/FwAX/xcAF/8XABf/IQAh/1MAU/9zAHP/fQB9/6YApv8AAAD/WYyR/4PZ4f+R9f7/kPb+/5H2//+R9v//kPb+/5H1/v+Q9f7/kPb//5D2/v+Q9v7/kPb//7P4/v/Q+/7/rcnM/wAAAP8AAAAAAAAAAAAAAAAAAAAoHiEnhE9XZf+30v//WGiE/xkfKP8oKCj/gICA/+rq6v/MzMz/ioqK/1dgbv9nfaP/jrDq/0Zkmf8AAAD/JAAk/y0ALf9GAEb/awBr/2sAa/9FAEX/RQBF/zcAN/9YAFj/lgCW/4wAjP9rAGv/NjJJ/1iNkf+B1t3/kfX+/5H1//+R9f//kfb//5H2//+R9v//kPX//5H2//+R9v//kPX//7z5///Z/P//rcnM/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAHgAAAJh3hJn/Fxoe/wAAAP8AAAD/Hh4e/5mZmf/g4OD/0NDQ/1FRUf9ATmb/m8D//4az//8uQ2X/LkNl/xIaKP8qACr/awBr/2sAa/+MAIz/eAB4/1gAWP9VAFX/bABs/3MAc/+ZAJn/HgAe/z1eYf93wcf/kfX+/5H1//+R9f//kfb//5H1//+R9v//kfb//5H2//+R9v//qPf//8f6///f/P//ucrM/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMAAAA9AAAAP8UFBT/KCgo/wAAAP//////1tbW/1FRUf9ATmb/ocT//6HE//9to///baP//zVShP8JER7/AAAA/wAAAP+PAI//ggCC/5YAlv9jAGP/GQAZ/38Af/9/AH//QhNC/0VVYv9rrrT/kfX+/5H2//+R9v//kfX//5H2/v+R9v//kfb+/5H2//+f9///zfv+/938/v/Y6er/qqqq9AAAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAAAAP9mZmb/zMzM/wAAAP//////1tbW/1FRUf9ATmb/oMT//6HE//9PkP//T5D//0+Q//8vVpn/AAAA/wAAAP8AAAD/jwCP/4wAjP9FAEX/IwAj/7MAs/+zALP/72Hv/2UwZf85YmX/kfb//5H2//+R9v//kfb//5H2//+R9f//kfb//5H2///Z/P//2fz//+/9//+YmJj/AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAAAAP8AAAD/AAAA/wAAAP//////1tbW/1FRUf9ATmb/oMT//6HE//8AAAD/AAAA/wAAAP9ATmX/ocT//6HE//+hxP//ICcz/0UARf9zAHP/WwBb/wAAAP9zAHP/4mHi/2UwZf85YmX/kfb//5H2//+R9v//kfb//5H2//+R9f//n/f//9n8///Z/P//9/7///////+YmJj/AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAAAAP8AAAD/KCgo/8zMzP//////U1NT/11uiv+NrOD/ocT//6DE//+AnMz/gJzM/4CczP+NrOD/h6TW/yAnMv8gJzL/BgcK/0UARf9zAHP/WwBb/wAAAP9zAHP/4mHi/2UwZf85YmX/kfb//5H2//+R9v//kfb//5H2//+o9/7/zfv+/9n8///3/v///f7+/4SEhP8sLCysAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUgAAAMIAAAD/FBQU/2ZmZv9mZmb/YXKO/4ek1v+hxP//ocT//6HE//9ATmb/QE5m/0BOZv9ATmb/Mz5R/wAAAP9EAET/RABE/2AAYP9zAHP/WwBb/wAAAP+ZAJn/6mHq/2UwZf85YmX/kfb//5H2//+R9v//kfb//5D2/v+t+P//2Pv+/9n8/////////v7+/2ZmZv8AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgfIyj/T1hm/09YZv9ATmb/jazg/6HE//+hxP//lLTq/2B1mP8AAAD/JAAk/y4ALv84ADj/QgBC/y4ALv+MAIz/eAB4/3MAc/9gAGD/RQBF/0cAR//RMNH/9Wv1/2UwZf85YmX/kfb//5H2//+R9v//kfb//5H2//+t+P7/2fz+/9n8/////////v7+/2ZmZv8AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHpIUFzgp7jW/8bb//+oyP//osT//6HE/v+UtOr/a32n/xYAFv8WABb/TgBO/2kAaf+MAIz/pgCm/3MAc/+mAKb/hwCH/2oAav9FAEX/PQA9/6YApv//ef//1mbW/2JEcP9Lf4T/kfb//5H2//+R9v//kfb//5n2//+2+f//2fv//9n8////////1tbW/1xcXOAAAAB6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmJysy/8fc///H3P//qMj//6HE//9gdZj/FgAW/3MAc/9zAHP/FgAW/0UARf+MAIz/pgCm/3MAc/9zAHP/pgCm/0cAR/9HAEf/pgCm/3MAc///ev//Mxgz/1eTmf+R9v//kfb//5H2//+R9v//kfb//7z5///Y+///2fz//9n8////////MjIy/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
